// src/stenciljs/components/button-stencil/button-stencil.tsx
import { Component, Event, EventEmitter, h, JSX, Prop } from '@stencil/core';

@Component({
  tag: 'button-stencil',
  styleUrl: 'button-stencil.css',
  shadow: true
})
export class Button {
  /**
   * Disabled button
   */
  @Prop() public disabled: boolean = false;

  /**
   * Variation of the button
   * Available variations are primary, secondary, buy
   */
  @Prop() public variation: string = 'primary';

  /**
   * Decides if the button should
   * be a small button
   */
  @Prop() public small: boolean = false;

  /**
   * Decides the type
   */
  @Prop() public type: string = 'type';

  /**
   * Decides the name
   */
  @Prop() public name: string = 'name';

  /**
   * Decides the Id
   * a unique id will be created
   */
  @Prop() public componentId: string = '';

  /**
   * Decides the ariaLabel
   */
  @Prop() public ariaLabel: string = '';

  /**
   * Decides if you want an loader
   * on the button
   */
  @Prop() public hasLoader: boolean = false;

  /**
   * Decides if the button is loading
   */
  @Prop() public loading: boolean = false;

  /**
   * the button text
   */
  @Prop() public text!: string;

  /**
   * loading state
   */
  @Prop() public messageHasLoaded: string = '';

  /**
   * loading state
   */
  @Prop() public messageLoading: string = '';

  /**
   * OnClick event
   */
  @Event({
    eventName: 'clickHandler',
    composed: true,
    cancelable: true,
    bubbles: true
  })
  public clickHandler: EventEmitter;

  private _clickHandler: any = (e: MouseEvent) => {
    if (this.clickHandler && !this.disabled && !this.loading) {
      this.clickHandler.emit(e);
    }
  };

  private _modifiers: any = () => {
    return {
      'IcaButton--primary': !this.disabled && (!this.variation || this.variation === `primary`),
      'IcaButton--secondary': !this.disabled && this.variation === `secondary`,
      'IcaButton--buy': !this.disabled && this.variation === `buy`,
      'IcaButton--disabled': this.disabled,
      'IcaButton--small': this.small,
      IcaButton: true
    };
  };

  private _labelModifiers: any = () => {
    return {
      'IcaButton__label--inactive': this.hasLoader && this.loading,
      IcaButton__label: true,
      lIcaButton__label: true
    };
  };

  public render(): JSX.IntrinsicElements {
    return (
      <button
        class={this._modifiers()}
        disabled={this.disabled}
        type={this.type}
        name={this.name}
        id={this.componentId}
        aria-label={this.ariaLabel}
        onClick={this._clickHandler}
      >
        <div class="IcaButton__loader">
          <ica-loader
            messageHasLoaded={this.messageHasLoaded}
            messageLoading={this.messageLoading}
            loading={this.loading}
          />
        </div>
        <div class={this._labelModifiers()}>
          <slot name="first" />
          <span class="IcaButton__text">{this.text}</span>
          <slot name="last" />
        </div>
      </button>
    );
  }
}

// src/svelte/button-svelte.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let disabled = false;
  export let variation = 'primary';
  export let small = false;
  export let type = 'type';
  export let name = 'name';
  export let componentId = '';
  export let ariaLabel = '';
  export let hasLoader = false;
  export let loading = false;
  export let text;
  export let messageHasLoaded = '';
  export let messageLoading = '';

  //   $: modifiers = () => ({
  //     'IcaButton--primary': !disabled && (!variation || variation === `primary`),
  //     'IcaButton--secondary': !disabled && variation === `secondary`,
  //     'IcaButton--buy': !disabled && variation === `buy`,
  //     'IcaButton--disabled': disabled,
  //     'IcaButton--small': small,
  //     IcaButton: true
  //   });
  //   $: labelModifiers = () => ({
  //     'IcaButton__label--inactive': hasLoader && loading,
  //     IcaButton__label: true,
  //     lIcaButton__label: true
  //   });

  const clickHandler = (evt) => dispatch('click', evt);
</script>

<svelte:options tag="button-svelte" />

<button
  class={modifiers()}
  disabled={this.disabled}
  type={this.type}
  name={this.name}
  id={this.componentId}
  aria-label={this.ariaLabel}
  onClick={this._clickHandler}>
  <div class="IcaButton__loader">
    <ica-loader messageHasLoaded={this.messageHasLoaded} messageLoading={this.messageLoading} loading={this.loading} />
  </div>
  <div class={this._labelModifiers()}>
    <slot name="first" />
    <span class="IcaButton__text">{this.text}</span>
    <slot name="last" />
  </div>
</button>
